### ISSUE TITLE
V2 archival setup

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/main-wp-website-deployment#17]
The current website will, in the future be know as v2. (v1 being  the current old version)  On deployment of the new website, we will need a plan to make the V2 version available (and publically so) for a short time.   One version maintains the current setup, and the second method preserves the V2 version using the development docker images.

## Maintain current setup.

In this scenario, we would replicate the strategy that we use create the current rc.library.ucdavis.edu site.   This has the simplicity of following our current methodology, but requires a commited VM for the V2 server.  In this method we would

- Move the current `old.library.ucdavis.edu` to `v1.web.library.ucdavis.edu` 
- Snapshot current VM
- replicate snapshot unto a new VM
- Update wordpress database using a modification of Jame's current script (replace rc.library.ucdavis.edu with v2.library.ucdavis.edu)
- Add an alert bar saying this is an old version
- Make read-only
- Verify that .htaccess redirect *do not* go offsite
- Update robots.txt for no index

## Dockerized Version
In this scenario, we would use the local development dockerized site to archive a snapshot.  This is a bit more complicated to initialize, but can be maintained on the same blue/gold VM's as the current site.  We would also need to save the V1 docker images. The steps are similar: 

- Move the current `old.library.ucdavis.edu` to `v1.web.library.ucdavis.edu` 
- create deployment docker-compose ( in file://gold/etc/library-website/v1)
- rsync current website content.  We could probably try and do this by adding rsync into the wordpress image (at least one time).
- export current mysql database
- update database with host renaming script
- Add an alert bar saying this is an old version
- Make read-only
  - [This Freeze plugin](https://wordpress.org/plugins/freeze/#description) looks promising
- Verify that .htaccess redirect *do not* go offsite
- Update robots.txt for no index
- Update the redirections for `router.web.library.ucdavis.edu`  to include v2.library.ucdavis.edu
- bring the docker-compose set up

**Comment by qjhart** [comment]
@spelkey-ucd / @jrmerz  / @jniffenegger I was asked by @NeilWeingarten to create a set of tasks for the old library site to be added to the current go live list.  Above are two potential setups.  I prefer the docker version.  Let me know what you think.

**Comment by spelkey-ucd** [comment]
Personally, I would like access to v1 and v2 restricted to the staff vpn. Is this possible if they are hosted on blue/gold? @jniffenegger ? I have no idea how that bit of networking works...

**Comment by jniffenegger** [comment]
I cannot block sites at the firewall if they are all hosted on the same IP as it is the IP that the rules are set for. If this is to be hosted on the same server (IP) as the production site then restricted it will have to be done at the server via htaccess.

James Niffenegger
Unix Administrator
Shields Library - ITIS
UC Davis

________________________________________

**Comment by qjhart** [comment]
@spelkey-ucd  It's possible to use the router to limit access to the VPN , and / or adding a simple CAS identifier.  I think for v2, (the current site) It might be better to replicate that CAS authentication that we use for staff?

**Comment by qjhart** [comment]
I've added a [diagram](https://docs.google.com/drawings/d/1nw_3TyurSa4UEb4Z_4ah-3_XTW7Po3O8c-WtRltKBRg/edit?usp=sharing) that combines this with the production site, and the special collection redirect issues.
