### ISSUE TITLE
Google maps API key

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/main-wp-website-deployment#26]
I was doing some load testing today, and trying to browse the test site at the same time.  That seemed to work okay, however.  I'm am noticing this issue. Regaring google maps iframe

![image](https://user-images.githubusercontent.com/344953/181833618-35ac3616-d521-4c0d-993f-45a7133683e4.png)

I kinda think that I would have noticed this yesterday, but I guess I don't know that for sure.  I am pretty sure my load tester did not forward these requests along to google though (in case it's a # of request issue) 

I'll monitor and let you know if ever responds correctly.

**Comment by spelkey-ucd** [comment]
@UcDust @sbagg Can you make sure the API key you minted is authorized for library.ucdavis.edu ?

**Comment by UcDust** [comment]
I don't have permission to view or edit keys, @jrmerz could you help with this by chance?

**Comment by jrmerz** [comment]
Updated. @UcDust  let me know how things work.  Could take up to 5min.
